### ISSUE TITLE
Add C API for regular expressions

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#1632]
See miniSphere feature request here:
http://forums.spheredev.org/index.php/topic,1215.msg9623.html#msg9623

It would be nice to have Ecmascript code be able to pass a regular expression to e.g. a Duktape/C function and later be able to use the passed regexp to do pattern matching against arbitrary strings, all directly through the C API.

**Comment by svaarala** [comment]
First, for completeness, the current way to use RegExps (or any other Ecmascript binding without a C equivalent).

Unless a lot of RegExp instances are created all the time, it should be reasonably OK to just do:

```c
duk_get_global_string(ctx, "RegExp");
duk_push_string(ctx, "[a-z]+");
duk_new(ctx, 1);
```

For matching there are a few more steps which may matter if RegExps are used in a very performance critical section (but then, Duktape regexp engine is not fast in general so it's not an ideal match there):

```c
duk_get_prop_string(ctx, regex_idx, "exec");
duk_dup(ctx, regex_idx);
duk_push_string(ctx, "aiee");
duk_call_method(ctx, 1);
/* Inspect result. */
```

**Comment by svaarala** [comment]
As for adding to the C API, I don't see why not. A few issues with these particular API bindings:
- RegExp constructor takes a string source and string options. For C code the string options are somewhat weird (compared to ordinary flags) but since it's also used in script code, maybe it's OK.
- Some version compatibility risks: RegExp constructor gains new options that aren't representable as a string. Or custom RegExp features are exposed, and a new argument is needed in the API.
- RegExp match result is an object and each capture is a separate string in the result. Inspecting the result is not very convenient in C code. But I'm not sure how the regexp result with all the captures etc could be conveniently provided in a C API considering memory lifecycle issues, strings with NULs, etc.

**Comment by fatcerberus** [comment]
Right, I know I can just call the RegExp constructor/methods.  But that's not ideal for sandboxing because someone could overwrite RegExp and/or mutate the prototype. :)

**Comment by svaarala** [comment]
I know, just mentioned it for completeness because the Minisphere discussion seems to imply it can't be done from C API at all. In my opinion it can be done, and reasonably well for most cases when the RegExp is constructed at init and then used multiple times.

Mutating the RegExp binding is also more of a theoretical problem IMO. If user code did that, it would also break script code like `new RegExp()` or even `/[a-z]/` if the RegExp prototype object was mutated. It's not generally a big concern unless the sandboxed code is potentially hostile, as opposed to just careless.

But if it's an issue, you can just stash the RegExp constructor into the global stash on init and use the same method. This won't fix RegExp.prototype mutation though, but adding a C API wouldn't fix that issue I'm afraid.

Even so I do agree that a C API would be nice.

**Comment by fatcerberus** [comment]
> Mutating the RegExp binding is also more of a theoretical problem IMO. If user code did that, it would also break script code like new RegExp() or even /[a-z]/ if the RegExp prototype object was mutated. It's not generally a big concern unless the sandboxed code is potentially hostile, as opposed to just careless.

Agreed; I'm mostly thinking of user expectation here, i.e. principle of least surprise.  Obviously any hostile mutation of the `RegExp` prototype would prevent normal JS code from functioning properly like you say, but for non-hostile code, if someone were to "enhance" the RegExp object via monkey-patch, they might not expect (or want) those changes to extend to a function known to be implemented natively.

...I guess that's pretty theoretical too, though.  There's not a lot you can ultimately do to change the underlying behavior by monkey-patching RegExp methods.

> But if it's an issue, you can just stash the RegExp constructor into the global stash on init and use the same method. This won't fix RegExp.prototype mutation though, but adding a C API wouldn't fix that issue I'm afraid.

I don't understand.  Assuming a C API existed, I would expect it to access the internal regular expression engine directly, without involving the "userland" built-ins at all?  Although... I guess if one passed in a regular expression as `/.../` that would involve the RegExp prototype anyway, but that could be worked around by passing them as strings instead.

**Comment by svaarala** [comment]
Because the argument of "someone may mutate the built-ins" comes up from time to time, just a few notes on why that isn't generally a huge problem IMO and why I don't find the argument "X needs a C API because of sandboxing" very appealing.

Just generally, providing a C API for every case where some built-in might be tampered with by an application is not really a solution, unless one assumes that *every* Ecmascript API is eventually mirrored into the C API. If one doesn't assume that, then there's always one more API that might be needed by e.g. a module loader, etc, which leads to a gradual pressure to expand the C API to fully match the Ecmascript API. If that's not an OK outcome (and I don't think it is), then the process has to stop somewhere.

Also, if one is truly trying to prevent user code from breaking built-in objects, all the objects need to be sealed and frozen manually before any user code runs.

if one does that, then both script code and C code are protected against modifications, and things like:

```c
duk_eval_string(ctx, "new RegExp('[a-z]+');");
```

and

```js
var re = new RegExp('[a-z]+');
```

will be equally protected from tampering.

As far as I can imagine, the main case where stronger stability guarantees provided by a C APi matters is e.g. where:
- Some "platform" mechanisms (like a module loader) runs in the same Duktape context and one wants to protected those mechanisms from being tampered with.
- It's still OK for the application to break its own environment, e.g. by mutating or deleting built-ins - and it's important that the platform mechanisms still continue to work as before.

But if this is the basic scenario, I'd probably just isolate e.g. a module loader completely by running it in a different context (in the same heap). This is very cheap, and protects against a lot of tampering in one step, and doesn't prevent using Ecmascript built-ins which one needs from time to time.

The main sandboxing cases that I've frequently come across are:
- Protecting application code from accidents. Configurable but non-writable properties are generally good enough for that because a Object.defineProperty() call is rarely an accident.
- Protecting against a truly hostile application. This requires a lot of measures beyond just protecting built-ins, e.g. censoring of tracebacks and careful analysis of every native binding for escalation possibilities.

**Comment by svaarala** [comment]
> > But if it's an issue, you can just stash the RegExp constructor into the global stash on init and use the same method. This won't fix RegExp.prototype mutation though, but adding a C API wouldn't fix that issue I'm afraid.
> I don't understand. Assuming a C API existed, I would expect it to access the internal regular expression engine directly, without involving the "userland" built-ins at all? Although... I guess if one passed in a regular expression as /.../ that would involve the RegExp prototype anyway, but that could be worked around by passing them as strings instead.

The most obvious implementation would be that a C API allowed one to create a RegExp instance. Many properties of RegExp instances like `.source`, `.global`, etc are inherited getters, and they're inherited from the RegExp prototype.

If they didn't inherit from the RegExp prototype, then they'd really be a different data type rather than an API to work with RegExp instances.

**Comment by fatcerberus** [comment]
> It's still OK for the application to break its own environment, e.g. by mutating or deleting built-ins - and it's important that the platform mechanisms still continue to work as before.

Right, this is my approach whenever possible.  I mostly try to separate "userland" from "kernel/engine space" to avoid surprising users and having to use eval runs counter to that :)

Obviously an experienced JS coder is going to know not to overwrite built-ins, but someone just learning about JavaScript (and Sphere is heavily geared towards newbies :) may accidentally overwrite a built-in with their own global variable.  I've actually seen code that does just that which worked fine in the old Sphere 1.x but broke in early versions of miniSphere because they assumed the constructors wouldn't be overwritten.

**Comment by svaarala** [comment]
So maybe what you'd really want is access to the regexp engine directly, rather than a C API to deal with RegExp instances?

Conceptually that'd be straightforward to do, but in practice it's not trivial to avoid the RegExp instance or the RegExp match result object because the internal code revolves around passing objects. There's no lower level representation for RegExps or RegExp match results.

The next best thing would be the ability to create a RegExp instance which didn't inherit from RegExp prototype and would thus be free of any outside influence. You could still match against it using a C API which wouldn't need to look up a match method from the prototype, but such RegExps wouldn't work in the script side.

**Comment by svaarala** [comment]
> Obviously an experienced JS coder is going to know not to overwrite built-ins, but someone just learning about JavaScript (and Sphere is heavily geared towards newbies :) may accidentally overwrite a built-in with their own global variable.

True. It would be easier to avoid accidents if all built-in bindings were non-writable but configurable. That way all write attempts would fail by default and you'd need to think a bit more if you really want to redefine the built-in. Unfortunately many built-ins are writable :-/

Btw, here's an example of what happens with Node.js interactive session when one overwrites RegExp.prototype.test:

```
$ nodejs
> RegExp.prototype.test = 123
123
> readline.js:924
            throw err;
            ^

TypeError: /^[0-9A-Za-z]$/.test is not a function
    at emitKeys (readline.js:1239:32)
    at next (native)
    at ReadStream.onData (readline.js:918:36)
    at emitOne (events.js:77:13)
    at ReadStream.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at ReadStream.Readable.push (_stream_readable.js:110:10)
    at TTY.onread (net.js:523:20)
```

**Comment by fatcerberus** [comment]
> So maybe what you'd really want is access to the regexp engine directly, rather than a C API to deal with RegExp instances?

Yes, this would be ideal.  I also wanted users to be able to pass regular expressions as `/.../` too but I guess I can't have it both ways :)

> Conceptually that'd be straightforward to do, but in practice it's not trivial to avoid the RegExp instance or the RegExp match result object because the internal code revolves around passing objects. There's no lower level representation for RegExps or RegExp match results.

I empathize with this, very much so.  Early in miniSphere's life several objects were represented only in the Ecmascript environment without a persistent C-side counterpart.  Nowadays almost every built-in class has a native reference-counted equivalent but that wasn't true back then and it often made it hard to compose things internally.

**Comment by fatcerberus** [comment]
Long story short: I want to use Duktape in lieu of adding another dependency for regular expression handling, but still outside the context of the Ecmascript environment if possible.  Sorry for not just coming out and saying that before. :-)

**Comment by svaarala** [comment]
Supposing the regexp API was not Ecmascript-inspired but optimized for C callers instead, how would that look like?

**Comment by fatcerberus** [comment]
I'd have to think about that for a bit to give you an answer to that question.  Maybe it would help to look at other regular expression engines for some inspiration, hmm...

**Comment by svaarala** [comment]
Conceptually at least:
- Compiling a regexp, with a set of options (at least flags or a flag string 'gi' as in Ecmascript).
- Running a regexp against an input string, probably interpreted as CESU-8.
- Checking for match or no match.
- Extracting captures.
- Continuing matching from previous position (for "find all").

**Comment by svaarala** [comment]
On a related note: I know a few projects that use Duktape for JSON encoding/decoding, choosing it over a JSON library because the API is good enough for that purpose (e.g. automatic memory management via value stack is easy to understand) and because it provides a way forward if it becomes necessary to use more features. This regexp use case is somewhat similar. Duktape isn't really designed with that in mind though, but it's nice if it works out at least in some cases.

Btw, a long time ago when I wrote the regexp compiler/executor I first tried to write it as a separate library rather than it being deeply integrated with the Ecmascript semantics. This turned out to be too difficult in practice so I gave up on that goal. It's certainly doable, but there would be a relatively large intermediate API and a significant footprint impact (relatively speaking, of course) due to that API.

**Comment by fatcerberus** [comment]
I've been known to use Duktape's JSON functionality to the same end.  I figure I'm already compiling in code to parse and interpret JSON data, why not take advantage of it?  So it's kind of the same rationale here with regexps, why add an additional dependency when I already have access to code that does everything I need :)

**Comment by fatcerberus** [comment]
Hm, thinking about the sandboxing issue some more, I guess it would be easy enough just to create an additional context which wouldn't be used to run "untrusted" code and therefore would remain isolated from the uncertainties of arbitrary code execution.

Of course that kind of thing wouldn't be practical on low-memory targets, but on desktop platforms the additional heap might as well be free.

**Comment by svaarala** [comment]
It doesn't even need to be a separate Duktape heap for isolation: two contexts created with separate global objects don't share any objects by default. You can exchange objects between them though and must be careful to avoid that. But for example a module loader can just pass in a string and pass back another string, and both contexts will live in entirely separated global object spaces.
