### ISSUE TITLE
duktape dislikes `interface`

### ISSUE THREAD

**Issue by mike-lischke** [svaarala/duktape#1702]
This is a rather strange issue. I'm using duktape 2.1.0 in case this matters. As soon as I use the string `interface` in a script duktape fails to parse it. A formerly parsing and running fine script fails when I add this line:

    console.log(interface);

or

    var interface = 0;

with the error: `SyntaxError: invalid variable declaration`. Seems "interface" has a special meaning for the duktape parser.

**Comment by mike-lischke** [comment]
Oh my, looking at the list of reserved words explains everything. Thanks for listening.

**Comment by svaarala** [comment]
It's indeed a reserved word issue, though only for strict mode code:

```
((o) Duktape [linenoise] 2.0.99 (v2.0.0-442-g865043d8)
duk> var interface = 123;
= undefined
duk> function foo() { var interface = 123; }
= undefined
duk> function bar() { 'use strict'; var interface = 123; }
SyntaxError: invalid variable declaration (line 1)
    at [anon] (input:1) internal
    at [anon] (duk_js_compiler.c:5027) internal
```

For comparison, Node.js:

```
> var interface = 123;
undefined
> function foo() { var interface = 123; }
undefined
> function bar() { 'use strict'; var interface = 123; }
SyntaxError: Unexpected strict mode reserved word
    at Object.exports.createScript (vm.js:24:10)
    at REPLServer.defaultEval (repl.js:225:25)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:417:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
    at REPLServer.Interface._onLine (readline.js:210:10)
    at REPLServer.Interface._line (readline.js:549:8)
    at REPLServer.Interface._ttyWrite (readline.js:826:14)
```
