### ISSUE TITLE
Duktape 2.0 > does not install on Windows 10 x64 

### ISSUE THREAD

**Issue by RailsCod3rFuture** [svaarala/duktape#1970]
Will you add Windows 10 support for your gem in the near future? I'm trying to use it for Rails 5.2, but I receive the error that's showing below.

```
Error:[rake --prereqs] C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.4/lib/bundler/resolver.rb:285:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'duktape (>= 2.0.1.0, ~> 2.0) x64-mingw32' in any of the gem sources listed in your Gemfile or in gems cached in vendor/cache. (Bundler::GemNotFound)
	from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.4/lib/bundler/resolver.rb:253:in `each'
	from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.4/lib/bundler/resolver.rb:253:in `verify_gemfile_dependencies_are_found!'
	from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.4/lib/bundler/resolver.rb:48:in `start'
	from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.4/lib/bundler/resolver.rb:22:in `resolve'
	from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.4/lib/bundler/definition.rb:258:in `resolve'
	from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.4/lib/bundler/definition.rb:171:in `specs'
	from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.4/lib/bundler/definition.rb:238:in `specs_for'
	from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.4/lib/bundler/definition.rb:227:in `requested_specs'
	from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.4/lib/bundler/runtime.rb:108:in `block in definition_method'
	from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.4/lib/bundler/runtime.rb:20:in `setup'
	from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.4/lib/bundler.rb:107:in `setup'
	from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.4/lib/bundler/setup.rb:20:in `<top (required)>'
	from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```

**Comment by svaarala** [comment]
This issue should probably go to https://github.com/judofyr/duktape.rb.

**Comment by RailsCod3rFuture** [comment]
ok. Thanks.

**Comment by RailsCod3rFuture** [comment]
It works now. I needed to update my ruby gem set.
