### ISSUE TITLE
Segmentation fault in duk__base64_decode_helper

### ISSUE THREAD

**Issue by renatahodovan** [svaarala/duktape#2027]
###### Duktape version:

```
Checked revision: b062b50a
```

###### OS:

```
Ubuntu 18.04, x86_64
```

###### Test case:

```javascript
function decPrint(x) { 
    SyntaxError(decPrint(Duktape.dec('base64', x)));
}

decPrint("");
```

###### Backtrace:

```
Program received signal SIGSEGV, Segmentation fault.
0x0000555555562ab7 in duk__base64_decode_helper (src=0x0, srclen=0, dst=0x5555559a5bc0 "", out_dst_final=0x7fffffff9be8)
    at prep/fuzz/duktape.c:15032
15032               t1 = (duk_int_t) duk__base64_dectab_fast[p[0]];
(gdb) bt
#0  0x0000555555562ab7 in duk__base64_decode_helper (src=0x0, srclen=0, dst=0x5555559a5bc0 "", out_dst_final=0x7fffffff9be8)
    at prep/fuzz/duktape.c:15032
#1  0x000055555556359c in duk_base64_decode (thr=0x555555991680, idx=1) at prep/fuzz/duktape.c:15381
#2  0x00005555555c33a5 in duk_bi_duktape_object_dec (thr=0x555555991680) at prep/fuzz/duktape.c:32043
#3  0x00005555555f8cdb in duk__handle_call_raw (thr=0x555555991680, idx_func=6, call_flags=8) at prep/fuzz/duktape.c:64343
#4  0x00005555555f9802 in duk_handle_call_unprotected (thr=0x555555991680, idx_func=6, call_flags=8) at prep/fuzz/duktape.c:64489
#5  0x000055555560c40c in duk__executor_handle_call (thr=0x555555991680, idx=6, nargs=2, call_flags=8) at prep/fuzz/duktape.c:75751
#6  0x0000555555631497 in duk__js_execute_bytecode_inner (entry_thread=0x555555991680, entry_act=0x55555599f7a0)
    at prep/fuzz/duktape.c:77825
#7  0x000055555560c80e in duk_js_execute_bytecode (exec_thr=0x555555991680) at prep/fuzz/duktape.c:76013
#8  0x00005555555f8aea in duk__handle_call_raw (thr=0x555555991680, idx_func=3, call_flags=0) at prep/fuzz/duktape.c:64307
#9  0x00005555555f9802 in duk_handle_call_unprotected (thr=0x555555991680, idx_func=3, call_flags=0) at prep/fuzz/duktape.c:64489
#10 0x000055555555edc1 in duk_call_method (thr=0x555555991680, nargs=0) at prep/fuzz/duktape.c:14352
#11 0x00005555556463ce in wrapped_compile_execute (ctx=0x555555991680, udata=0x0) at examples/cmdline/duk_cmdline.c:301
#12 0x00005555555f9b41 in duk__handle_safe_call_inner (thr=0x555555991680, func=0x555555646129 <wrapped_compile_execute>, 
    udata=0x0, entry_valstack_bottom_byteoff=0, entry_callstack_top=0, entry_curr_thread=0x0, entry_thread_state=1 '\001', 
    idx_retbase=0, num_stack_rets=1) at prep/fuzz/duktape.c:64542
#13 0x00005555555fa95e in duk_handle_safe_call (thr=0x555555991680, func=0x555555646129 <wrapped_compile_execute>, udata=0x0, 
    num_stack_args=4, num_stack_rets=1) at prep/fuzz/duktape.c:64787
#14 0x000055555556085e in duk_safe_call (thr=0x555555991680, func=0x555555646129 <wrapped_compile_execute>, udata=0x0, nargs=4, 
    nrets=1) at prep/fuzz/duktape.c:14520
#15 0x0000555555646601 in handle_fh (ctx=0x555555991680, f=0x5555559a3280, filename=0x7fffffffe487 "test.js", 
    bytecode_filename=0x0) at examples/cmdline/duk_cmdline.c:632
#16 0x00005555556467ce in handle_file (ctx=0x555555991680, filename=0x7fffffffe487 "test.js", bytecode_filename=0x0)
    at examples/cmdline/duk_cmdline.c:691
#17 0x000055555564724b in main (argc=2, argv=0x7fffffffe1a8) at examples/cmdline/duk_cmdline.c:1465
```

###### Build script:

```bash
#!/bin/bash

git reset --hard origin/master
git pull origin master
rm -rf prep/fuzz duk
mkdir -p prep/fuzz

python2 tools/configure.py --output-directory prep/fuzz --source-directory src-input --config-metadata config --option-file $(dirname $0)/duktape-fuzzinator-options.yaml

gcc -o duk \
    -Iprep/fuzz \
    -D_POSIX_C_SOURCE=200809L \
    -pedantic -ansi -std=c99 -fstrict-aliasing -Wall -Wextra -Wunused-result -Wdeclaration-after-statement -Wunused-function -Wcast-qual -Wcast-align -Wshadow -Wunreachable-code   -Wmissing-prototypes -Wsign-conversion -Wsuggest-attribute=noreturn -fmax-errors=3 \
    -Ilinenoise \
    -Iexamples/cmdline \
    -Iexamples/alloc-logging \
    -Iexamples/alloc-torture \
    -Iexamples/alloc-hybrid \
    -Iexamples/debug-trans-socket \
    -Iextras/print-alert \
    -Iextras/console \
    -Iextras/logging \
    -Iextras/module-duktape \
    -Iextras/cbor \
    -O0 -g -ggdb \
    prep/fuzz/duktape.c \
    examples/cmdline/duk_cmdline.c \
    examples/alloc-logging/duk_alloc_logging.c \
    examples/alloc-torture/duk_alloc_torture.c \
    examples/alloc-hybrid/duk_alloc_hybrid.c \
    extras/print-alert/duk_print_alert.c \
    extras/console/duk_console.c \
    extras/logging/duk_logging.c \
    extras/module-duktape/duk_module_duktape.c \
    extras/cbor/duk_cbor.c \
    examples/debug-trans-socket/duk_trans_socket_unix.c \
    linenoise/linenoise.c \
    -lm

```

###### duktape-fuzzinator-options.yaml:

```yaml
DUK_USE_ASSERTIONS: true
DUK_USE_DEBUG: false

DUK_USE_ES6_OBJECT_PROTO_PROPERTY: true
DUK_USE_JX: true
DUK_USE_JC: true

DUK_USE_NONSTD_ARRAY_SPLICE_DELCOUNT: true
DUK_USE_NONSTD_JSON_ESC_U2028_U2029: true
DUK_USE_NONSTD_STRING_FROMCHARCODE_32BIT: true
DUK_USE_ES6_OBJECT_PROTO_PROPERTY: true
DUK_USE_ES6_OBJECT_SETPROTOTYPEOF: true
DUK_USE_ES6_PROXY: true
DUK_USE_ZERO_BUFFER_DATA: true
DUK_USE_SETJMP: true
DUK_USE_LIGHTFUNC_BUILTINS: true
DUK_USE_BUFFEROBJECT_SUPPORT: true
DUK_USE_FASTINT: true
DUK_USE_JSON_STRINGIFY_FASTPATH: true
DUK_USE_GLOBAL_BINDING: true
DUK_USE_PROMISE_BUILTIN: true

DUK_USE_FATAL_HANDLER:
  verbatim: |
    #define DUK_USE_FATAL_HANDLER(udata,msg) do { \
            const char *fatal_msg = (msg); /* avoid double evaluation */ \
            (void) udata; \
            fprintf(stderr, "*** FATAL ERROR: %s\n", fatal_msg ? fatal_msg : "no message"); \
            fflush(stderr); \
            abort(); \
        } while (0)

```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/) with [grammarinator](https://github.com/renatahodovan/grammarinator). </sup>

**Comment by svaarala** [comment]
The root cause is that some types of zero-length buffer are handled incorrectly. Simplified repro:
```
var t1 = Duktape.dec('base64', '');  // creates offending buffer value
var t2 = Duktape.dec('base64', t1);  // segfault
```
