### ISSUE TITLE
assertion failed: thr->heap->ms_running == 0 || thr == thr->heap->heap_thread in duk_heaphdr_refzero

### ISSUE THREAD

**Issue by renatahodovan** [svaarala/duktape#2030]
###### Duktape version:

```
Checked revision: b062b50a
```

###### OS:

```
Ubuntu 18.04, x86_64
```

###### Test case:

```javascript
Duktape.fin( 
    Proxy, function( ) { 
        function f( ) { 
            performance ('g called', isFinite(Error), TypeError(g)); 
        }
        Duktape.Thread.resume(new Duktape.Thread(f)); 
});
```

###### Backtrace:

```
*** FATAL ERROR: assertion failed: thr->heap->ms_running == 0 || thr == thr->heap->heap_thread (prep/fuzz/duktape.c:51347)

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51  ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff7686801 in __GI_abort () at abort.c:79
#2  0x000055555555759f in duk_default_fatal_handler (msg=<optimized out>, 
    msg@entry=0x55555590ee78 "assertion failed: thr->heap->ms_running == 0 || thr == thr->heap->heap_thread (prep/fuzz/duktape.c:51347)", udata=udata@entry=0x55555590ee78) at prep/fuzz/duktape.c:11792
#3  0x0000555555675bbc in duk__heaphdr_refzero_helper (skip_free_pending=0, h=0x555555bd8b90, thr=<optimized out>)
    at prep/fuzz/duktape.c:51347
#4  duk_heaphdr_refzero (thr=<optimized out>, h=0x555555bd8b90) at prep/fuzz/duktape.c:51381
#5  0x0000555555676590 in duk__pop_unsafe_raw (thr=0x555555bdc520) at prep/fuzz/duktape.c:23581
#6  duk_pop_unsafe (thr=thr@entry=0x555555bdc520) at prep/fuzz/duktape.c:23601
#7  0x000055555560a791 in duk_js_tonumber (thr=thr@entry=0x555555bdc520, tv=tv@entry=0x555555bd9930) at prep/fuzz/duktape.c:78553
#8  0x00005555556858f8 in duk_to_number (thr=thr@entry=0x555555bdc520, idx=idx@entry=0) at prep/fuzz/duktape.c:20400
#9  0x00005555556883e3 in duk_bi_global_object_is_finite (thr=0x555555bdc520) at prep/fuzz/duktape.c:34149
#10 0x000055555561f5b7 in duk__handle_call_raw (thr=thr@entry=0x555555bdc520, idx_func=idx_func@entry=3, 
    call_flags=call_flags@entry=8) at prep/fuzz/duktape.c:64343
#11 0x000055555556116d in duk_handle_call_unprotected (call_flags=8, idx_func=3, thr=0x555555bdc520) at prep/fuzz/duktape.c:64489
#12 duk__executor_handle_call (call_flags=8, nargs=1, idx=3, thr=0x555555bdc520) at prep/fuzz/duktape.c:10215
#13 duk__js_execute_bytecode_inner (entry_act=entry_act@entry=0x555555bcea20, entry_thread=<optimized out>)
    at prep/fuzz/duktape.c:12289
#14 0x0000555555614f86 in duk_js_execute_bytecode (exec_thr=exec_thr@entry=0x555555bc7680) at prep/fuzz/duktape.c:76013
#15 0x000055555561db30 in duk__handle_call_raw (thr=thr@entry=0x555555bc7680, idx_func=<optimized out>, 
    call_flags=call_flags@entry=0) at prep/fuzz/duktape.c:64307
#16 0x00005555557cf03e in duk_handle_call_unprotected (call_flags=0, idx_func=<optimized out>, thr=0x555555bc7680)
    at prep/fuzz/duktape.c:64489
#17 duk_call (thr=thr@entry=0x555555bc7680, nargs=<optimized out>, nargs@entry=2) at prep/fuzz/duktape.c:14339
#18 0x00005555557cf6a0 in duk__finalize_helper (thr=thr@entry=0x555555bc7680, udata=udata@entry=0x0) at prep/fuzz/duktape.c:48543
#19 0x00005555556370a7 in duk__handle_safe_call_inner (num_stack_rets=1, idx_retbase=1, entry_thread_state=1 '\001', 
    entry_curr_thread=0x0, entry_callstack_top=0, entry_valstack_bottom_byteoff=0, udata=0x0, 
    func=0x5555557cf5f0 <duk__finalize_helper>, thr=0x555555bc7680) at prep/fuzz/duktape.c:64542
#20 duk_handle_safe_call (thr=thr@entry=0x555555bc7680, func=func@entry=0x5555557cf5f0 <duk__finalize_helper>, 
    udata=udata@entry=0x0, num_stack_args=num_stack_args@entry=0, num_stack_rets=num_stack_rets@entry=1)
    at prep/fuzz/duktape.c:64787
#21 0x0000555555639296 in duk_safe_call (thr=thr@entry=0x555555bc7680, func=func@entry=0x5555557cf5f0 <duk__finalize_helper>, 
    udata=udata@entry=0x0, nargs=nargs@entry=0, nrets=nrets@entry=1) at prep/fuzz/duktape.c:14520
#22 0x00005555556983b0 in duk_heap_run_finalizer (obj=0x555555bc9cc0, heap=0x555555bc1260) at prep/fuzz/duktape.c:48607
#23 duk__free_run_finalizers (heap=0x555555bc1260) at prep/fuzz/duktape.c:47247
#24 duk_heap_free (heap=0x555555bc1260) at prep/fuzz/duktape.c:47354
#25 0x000055555555c7c0 in destroy_duktape_heap (alloc_provider=<optimized out>, ctx=0x555555bc7680)
    at examples/cmdline/duk_cmdline.c:1254
#26 main (argc=<optimized out>, argv=<optimized out>) at examples/cmdline/duk_cmdline.c:1528
```

###### Build script:

```bash
#!/bin/bash

git reset --hard origin/master
git pull origin master
rm -rf prep/fuzz duk
mkdir -p prep/fuzz

python2 tools/configure.py --output-directory prep/fuzz --source-directory src-input --config-metadata config --option-file $(dirname $0)/duktape-fuzzinator-options.yaml

gcc -o duk \
    -Iprep/fuzz \
    -D_POSIX_C_SOURCE=200809L \
    -pedantic -ansi -std=c99 -fstrict-aliasing -Wall -Wextra -Wunused-result -Wdeclaration-after-statement -Wunused-function -Wcast-qual -Wcast-align -Wshadow -Wunreachable-code   -Wmissing-prototypes -Wsign-conversion -Wsuggest-attribute=noreturn -fmax-errors=3 \
    -Ilinenoise \
    -Iexamples/cmdline \
    -Iexamples/alloc-logging \
    -Iexamples/alloc-torture \
    -Iexamples/alloc-hybrid \
    -Iexamples/debug-trans-socket \
    -Iextras/print-alert \
    -Iextras/console \
    -Iextras/logging \
    -Iextras/module-duktape \
    -Iextras/cbor \
    -O0 -g -ggdb \
    prep/fuzz/duktape.c \
    examples/cmdline/duk_cmdline.c \
    examples/alloc-logging/duk_alloc_logging.c \
    examples/alloc-torture/duk_alloc_torture.c \
    examples/alloc-hybrid/duk_alloc_hybrid.c \
    extras/print-alert/duk_print_alert.c \
    extras/console/duk_console.c \
    extras/logging/duk_logging.c \
    extras/module-duktape/duk_module_duktape.c \
    extras/cbor/duk_cbor.c \
    examples/debug-trans-socket/duk_trans_socket_unix.c \
    linenoise/linenoise.c \
    -lm

```

###### duktape-fuzzinator-options.yaml:

```yaml
DUK_USE_ASSERTIONS: true
DUK_USE_DEBUG: false

DUK_USE_ES6_OBJECT_PROTO_PROPERTY: true
DUK_USE_JX: true
DUK_USE_JC: true

DUK_USE_NONSTD_ARRAY_SPLICE_DELCOUNT: true
DUK_USE_NONSTD_JSON_ESC_U2028_U2029: true
DUK_USE_NONSTD_STRING_FROMCHARCODE_32BIT: true
DUK_USE_ES6_OBJECT_PROTO_PROPERTY: true
DUK_USE_ES6_OBJECT_SETPROTOTYPEOF: true
DUK_USE_ES6_PROXY: true
DUK_USE_ZERO_BUFFER_DATA: true
DUK_USE_SETJMP: true
DUK_USE_LIGHTFUNC_BUILTINS: true
DUK_USE_BUFFEROBJECT_SUPPORT: true
DUK_USE_FASTINT: true
DUK_USE_JSON_STRINGIFY_FASTPATH: true
DUK_USE_GLOBAL_BINDING: true
DUK_USE_PROMISE_BUILTIN: true

DUK_USE_FATAL_HANDLER:
  verbatim: |
    #define DUK_USE_FATAL_HANDLER(udata,msg) do { \
            const char *fatal_msg = (msg); /* avoid double evaluation */ \
            (void) udata; \
            fprintf(stderr, "*** FATAL ERROR: %s\n", fatal_msg ? fatal_msg : "no message"); \
            fflush(stderr); \
            abort(); \
        } while (0)

```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/) with [grammarinator](https://github.com/renatahodovan/grammarinator). </sup>

**Comment by svaarala** [comment]
This assert is incorrect but probably harmless. The root cause is that we're freeing the heap and the Proxy built-in has a finalizer which creates a new Duktape coroutine, which then creates a heap object that gets refzeroed. The refzero code includes the failing assert.

The assert requires that either mark-and-sweep is not running, or if it is, we're running in the heap thread executing finalizers. The assert didn't anticipate that new coroutines could (or would) be created from within the finalizer.

I'll first check whether this behavior can simply be accepted. If not, the easiest fix is to refuse resuming (or maybe creating and resuming) coroutines from within a finalizer.

**Comment by svaarala** [comment]
This should actually happen only in heap destruction when remaining finalizers are executed. During those finalizers we set ms_running = 1 to prevent refzero handling. This differs from runtime mark-and-sweep where ms_running is already 0 when finalizers are executed (i.e. finalizers execute outside of mark-and-sweep). I'll issue a short term fix where the assertion is disabled as incorrect, but a better fix would be to use separate flags or detect the situation in asserts, so that stronger assertions could remain in place.
