### ISSUE TITLE
assertion failed: (thr)->valstack_end - (thr)->valstack_top >= (10) + DUK_VALSTACK_ASSERT_EXTRA in duk_hobject_getprop

### ISSUE THREAD

**Issue by renatahodovan** [svaarala/duktape#2032]
###### Duktape version:

```
Checked revision: b062b50a
```

###### OS:

```
Ubuntu 18.04, x86_64
```

###### Test case:

```javascript
f = function( ) { };
Object.defineProperty(f, 'length', { get : new Proxy ( Uint32Array , TextEncoder )});
JSON = f.bind(null, /x{11,111111111}/ );
```

###### Backtrace:

```
*** FATAL ERROR: assertion failed: (thr)->valstack_end - (thr)->valstack_top >= (10) + DUK_VALSTACK_ASSERT_EXTRA (prep/fuzz/duktape.c:56560)

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51  ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff7686801 in __GI_abort () at abort.c:79
#2  0x000055555555759f in duk_default_fatal_handler (msg=<optimized out>, 
    msg@entry=0x5555558f2218 "assertion failed: (thr)->valstack_end - (thr)->valstack_top >= (10) + DUK_VALSTACK_ASSERT_EXTRA (prep/fuzz/duktape.c:56560)", udata=udata@entry=0x5555558f2218) at prep/fuzz/duktape.c:11792
#3  0x000055555562e6fc in duk_hobject_getprop (thr=thr@entry=0x555555bc7680, tv_obj=tv_obj@entry=0x555555bc7f00, 
    tv_key=<optimized out>) at prep/fuzz/duktape.c:56560
#4  0x000055555562f26e in duk_get_prop (thr=0x555555bc7680, obj_idx=<optimized out>) at prep/fuzz/duktape.c:16625
#5  0x0000555555621d20 in duk_get_prop_stridx_short_raw (packed_args=4294901830, thr=0x555555bc7680) at prep/fuzz/duktape.c:16690
#6  duk__handle_proxy_for_call (call_flags=<synthetic pointer>, h_proxy=0x555555bd47d0, idx_func=<optimized out>, 
    thr=0x555555bc7680) at prep/fuzz/duktape.c:62986
#7  duk__resolve_target_func_and_this_binding (call_flags=<synthetic pointer>, idx_func=86, thr=0x555555bc7680)
    at prep/fuzz/duktape.c:63350
#8  duk__handle_call_raw (thr=thr@entry=0x555555bc7680, idx_func=86, call_flags=call_flags@entry=0) at prep/fuzz/duktape.c:64142
#9  0x0000555555626498 in duk_handle_call_unprotected (call_flags=0, idx_func=<optimized out>, thr=0x555555bc7680)
    at prep/fuzz/duktape.c:64489
#10 duk_call_method (thr=thr@entry=0x2711, nargs=<optimized out>, nargs@entry=1) at prep/fuzz/duktape.c:14352
#11 0x000055555562d0bb in duk_hobject_getprop (thr=0x2711, thr@entry=0x555555bc7680, tv_obj=0x7fffffffb580, 
    tv_obj@entry=0x555555bc7ea0, tv_key=0x7fffffffb590) at prep/fuzz/duktape.c:56912
#12 0x000055555562f26e in duk_get_prop (thr=0x555555bc7680, obj_idx=<optimized out>) at prep/fuzz/duktape.c:16625
#13 0x00005555557eb665 in duk_unpack_array_like (thr=thr@entry=0x555555bc7680, idx=idx@entry=83) at prep/fuzz/duktape.c:23859
#14 0x00005555556220cf in duk__handle_specialfuncs_for_call (first=<optimized out>, call_flags=<synthetic pointer>, 
    func=<optimized out>, idx_func=<optimized out>, thr=0x555555bc7680) at prep/fuzz/duktape.c:62935
#15 duk__resolve_target_func_and_this_binding (call_flags=<synthetic pointer>, idx_func=81, thr=0x555555bc7680)
    at prep/fuzz/duktape.c:63360
#16 duk__handle_call_raw (thr=thr@entry=0x555555bc7680, idx_func=81, call_flags=call_flags@entry=0) at prep/fuzz/duktape.c:64142
#17 0x0000555555626498 in duk_handle_call_unprotected (call_flags=0, idx_func=<optimized out>, thr=0x555555bc7680)
    at prep/fuzz/duktape.c:64489
#18 duk_call_method (thr=thr@entry=0x2711, nargs=<optimized out>, nargs@entry=1) at prep/fuzz/duktape.c:14352
#19 0x000055555562d0bb in duk_hobject_getprop (thr=0x2711, thr@entry=0x555555bc7680, tv_obj=0x7fffffffb760, 
    tv_obj@entry=0x555555bc7e50, tv_key=0x7fffffffb770) at prep/fuzz/duktape.c:56912
#20 0x000055555562f26e in duk_get_prop (thr=0x555555bc7680, obj_idx=<optimized out>) at prep/fuzz/duktape.c:16625
#21 0x00005555557eb665 in duk_unpack_array_like (thr=thr@entry=0x555555bc7680, idx=idx@entry=78) at prep/fuzz/duktape.c:23859
#22 0x00005555556220cf in duk__handle_specialfuncs_for_call (first=<optimized out>, call_flags=<synthetic pointer>, 
    func=<optimized out>, idx_func=<optimized out>, thr=0x555555bc7680) at prep/fuzz/duktape.c:62935
#23 duk__resolve_target_func_and_this_binding (call_flags=<synthetic pointer>, idx_func=76, thr=0x555555bc7680)
    at prep/fuzz/duktape.c:63360
#24 duk__handle_call_raw (thr=thr@entry=0x555555bc7680, idx_func=76, call_flags=call_flags@entry=0) at prep/fuzz/duktape.c:64142
#25 0x0000555555626498 in duk_handle_call_unprotected (call_flags=0, idx_func=<optimized out>, thr=0x555555bc7680)
    at prep/fuzz/duktape.c:64489
#26 duk_call_method (thr=thr@entry=0x2711, nargs=<optimized out>, nargs@entry=1) at prep/fuzz/duktape.c:14352
#27 0x000055555562d0bb in duk_hobject_getprop (thr=0x2711, thr@entry=0x555555bc7680, tv_obj=0x7fffffffb940, 
    tv_obj@entry=0x555555bc7e00, tv_key=0x7fffffffb950) at prep/fuzz/duktape.c:56912
#28 0x000055555562f26e in duk_get_prop (thr=0x555555bc7680, obj_idx=<optimized out>) at prep/fuzz/duktape.c:16625
#29 0x00005555557eb665 in duk_unpack_array_like (thr=thr@entry=0x555555bc7680, idx=idx@entry=73) at prep/fuzz/duktape.c:23859
#30 0x00005555556220cf in duk__handle_specialfuncs_for_call (first=<optimized out>, call_flags=<synthetic pointer>, 
    func=<optimized out>, idx_func=<optimized out>, thr=0x555555bc7680) at prep/fuzz/duktape.c:62935
#31 duk__resolve_target_func_and_this_binding (call_flags=<synthetic pointer>, idx_func=71, thr=0x555555bc7680)
    at prep/fuzz/duktape.c:63360
#32 duk__handle_call_raw (thr=thr@entry=0x555555bc7680, idx_func=71, call_flags=call_flags@entry=0) at prep/fuzz/duktape.c:64142
#33 0x0000555555626498 in duk_handle_call_unprotected (call_flags=0, idx_func=<optimized out>, thr=0x555555bc7680)
    at prep/fuzz/duktape.c:64489
#34 duk_call_method (thr=thr@entry=0x2711, nargs=<optimized out>, nargs@entry=1) at prep/fuzz/duktape.c:14352
#35 0x000055555562d0bb in duk_hobject_getprop (thr=0x2711, thr@entry=0x555555bc7680, tv_obj=0x7fffffffbb20, 
    tv_obj@entry=0x555555bc7db0, tv_key=0x7fffffffbb30) at prep/fuzz/duktape.c:56912
#36 0x000055555562f26e in duk_get_prop (thr=0x555555bc7680, obj_idx=<optimized out>) at prep/fuzz/duktape.c:16625
#37 0x00005555557eb665 in duk_unpack_array_like (thr=thr@entry=0x555555bc7680, idx=idx@entry=68) at prep/fuzz/duktape.c:23859
#38 0x00005555556220cf in duk__handle_specialfuncs_for_call (first=<optimized out>, call_flags=<synthetic pointer>, 
    func=<optimized out>, idx_func=<optimized out>, thr=0x555555bc7680) at prep/fuzz/duktape.c:62935
#39 duk__resolve_target_func_and_this_binding (call_flags=<synthetic pointer>, idx_func=66, thr=0x555555bc7680)
    at prep/fuzz/duktape.c:63360
#40 duk__handle_call_raw (thr=thr@entry=0x555555bc7680, idx_func=66, call_flags=call_flags@entry=0) at prep/fuzz/duktape.c:64142
#41 0x0000555555626498 in duk_handle_call_unprotected (call_flags=0, idx_func=<optimized out>, thr=0x555555bc7680)
    at prep/fuzz/duktape.c:64489
#42 duk_call_method (thr=thr@entry=0x2711, nargs=<optimized out>, nargs@entry=1) at prep/fuzz/duktape.c:14352
#43 0x000055555562d0bb in duk_hobject_getprop (thr=0x2711, thr@entry=0x555555bc7680, tv_obj=0x7fffffffbd00, 
    tv_obj@entry=0x555555bc7d60, tv_key=0x7fffffffbd10) at prep/fuzz/duktape.c:56912
#44 0x000055555562f26e in duk_get_prop (thr=0x555555bc7680, obj_idx=<optimized out>) at prep/fuzz/duktape.c:16625
#45 0x00005555557eb665 in duk_unpack_array_like (thr=thr@entry=0x555555bc7680, idx=idx@entry=63) at prep/fuzz/duktape.c:23859
#46 0x00005555556220cf in duk__handle_specialfuncs_for_call (first=<optimized out>, call_flags=<synthetic pointer>, 
    func=<optimized out>, idx_func=<optimized out>, thr=0x555555bc7680) at prep/fuzz/duktape.c:62935
#47 duk__resolve_target_func_and_this_binding (call_flags=<synthetic pointer>, idx_func=61, thr=0x555555bc7680)
    at prep/fuzz/duktape.c:63360
#48 duk__handle_call_raw (thr=thr@entry=0x555555bc7680, idx_func=61, call_flags=call_flags@entry=0) at prep/fuzz/duktape.c:64142
#49 0x0000555555626498 in duk_handle_call_unprotected (call_flags=0, idx_func=<optimized out>, thr=0x555555bc7680)
    at prep/fuzz/duktape.c:64489
#50 duk_call_method (thr=thr@entry=0x2711, nargs=<optimized out>, nargs@entry=1) at prep/fuzz/duktape.c:14352
#51 0x000055555562d0bb in duk_hobject_getprop (thr=0x2711, thr@entry=0x555555bc7680, tv_obj=0x7fffffffbee0, 
    tv_obj@entry=0x555555bc7d10, tv_key=0x7fffffffbef0) at prep/fuzz/duktape.c:56912
#52 0x000055555562f26e in duk_get_prop (thr=0x555555bc7680, obj_idx=<optimized out>) at prep/fuzz/duktape.c:16625
#53 0x00005555557eb665 in duk_unpack_array_like (thr=thr@entry=0x555555bc7680, idx=idx@entry=58) at prep/fuzz/duktape.c:23859
#54 0x00005555556220cf in duk__handle_specialfuncs_for_call (first=<optimized out>, call_flags=<synthetic pointer>, 
    func=<optimized out>, idx_func=<optimized out>, thr=0x555555bc7680) at prep/fuzz/duktape.c:62935
#55 duk__resolve_target_func_and_this_binding (call_flags=<synthetic pointer>, idx_func=56, thr=0x555555bc7680)
    at prep/fuzz/duktape.c:63360
#56 duk__handle_call_raw (thr=thr@entry=0x555555bc7680, idx_func=56, call_flags=call_flags@entry=0) at prep/fuzz/duktape.c:64142
#57 0x0000555555626498 in duk_handle_call_unprotected (call_flags=0, idx_func=<optimized out>, thr=0x555555bc7680)
    at prep/fuzz/duktape.c:64489
#58 duk_call_method (thr=thr@entry=0x2711, nargs=<optimized out>, nargs@entry=1) at prep/fuzz/duktape.c:14352
#59 0x000055555562d0bb in duk_hobject_getprop (thr=0x2711, thr@entry=0x555555bc7680, tv_obj=0x7fffffffc0c0, 
    tv_obj@entry=0x555555bc7cc0, tv_key=0x7fffffffc0d0) at prep/fuzz/duktape.c:56912
#60 0x000055555562f26e in duk_get_prop (thr=0x555555bc7680, obj_idx=<optimized out>) at prep/fuzz/duktape.c:16625
#61 0x00005555557eb665 in duk_unpack_array_like (thr=thr@entry=0x555555bc7680, idx=idx@entry=53) at prep/fuzz/duktape.c:23859
#62 0x00005555556220cf in duk__handle_specialfuncs_for_call (first=<optimized out>, call_flags=<synthetic pointer>, 
    func=<optimized out>, idx_func=<optimized out>, thr=0x555555bc7680) at prep/fuzz/duktape.c:62935
#63 duk__resolve_target_func_and_this_binding (call_flags=<synthetic pointer>, idx_func=51, thr=0x555555bc7680)
    at prep/fuzz/duktape.c:63360
#64 duk__handle_call_raw (thr=thr@entry=0x555555bc7680, idx_func=51, call_flags=call_flags@entry=0) at prep/fuzz/duktape.c:64142
#65 0x0000555555626498 in duk_handle_call_unprotected (call_flags=0, idx_func=<optimized out>, thr=0x555555bc7680)
    at prep/fuzz/duktape.c:64489
#66 duk_call_method (thr=thr@entry=0x2711, nargs=<optimized out>, nargs@entry=1) at prep/fuzz/duktape.c:14352
#67 0x000055555562d0bb in duk_hobject_getprop (thr=0x2711, thr@entry=0x555555bc7680, tv_obj=0x7fffffffc2a0, 
    tv_obj@entry=0x555555bc7c70, tv_key=0x7fffffffc2b0) at prep/fuzz/duktape.c:56912
#68 0x000055555562f26e in duk_get_prop (thr=0x555555bc7680, obj_idx=<optimized out>) at prep/fuzz/duktape.c:16625
#69 0x00005555557eb665 in duk_unpack_array_like (thr=thr@entry=0x555555bc7680, idx=idx@entry=48) at prep/fuzz/duktape.c:23859
#70 0x00005555556220cf in duk__handle_specialfuncs_for_call (first=<optimized out>, call_flags=<synthetic pointer>, 
    func=<optimized out>, idx_func=<optimized out>, thr=0x555555bc7680) at prep/fuzz/duktape.c:62935
#71 duk__resolve_target_func_and_this_binding (call_flags=<synthetic pointer>, idx_func=46, thr=0x555555bc7680)
    at prep/fuzz/duktape.c:63360
#72 duk__handle_call_raw (thr=thr@entry=0x555555bc7680, idx_func=46, call_flags=call_flags@entry=0) at prep/fuzz/duktape.c:64142
#73 0x0000555555626498 in duk_handle_call_unprotected (call_flags=0, idx_func=<optimized out>, thr=0x555555bc7680)
    at prep/fuzz/duktape.c:64489
#74 duk_call_method (thr=thr@entry=0x2711, nargs=<optimized out>, nargs@entry=1) at prep/fuzz/duktape.c:14352
#75 0x000055555562d0bb in duk_hobject_getprop (thr=0x2711, thr@entry=0x555555bc7680, tv_obj=0x7fffffffc480, 
    tv_obj@entry=0x555555bc7c20, tv_key=0x7fffffffc490) at prep/fuzz/duktape.c:56912
#76 0x000055555562f26e in duk_get_prop (thr=0x555555bc7680, obj_idx=<optimized out>) at prep/fuzz/duktape.c:16625
#77 0x00005555557eb665 in duk_unpack_array_like (thr=thr@entry=0x555555bc7680, idx=idx@entry=43) at prep/fuzz/duktape.c:23859
#78 0x00005555556220cf in duk__handle_specialfuncs_for_call (first=<optimized out>, call_flags=<synthetic pointer>, 
    func=<optimized out>, idx_func=<optimized out>, thr=0x555555bc7680) at prep/fuzz/duktape.c:62935
#79 duk__resolve_target_func_and_this_binding (call_flags=<synthetic pointer>, idx_func=41, thr=0x555555bc7680)
    at prep/fuzz/duktape.c:63360
#80 duk__handle_call_raw (thr=thr@entry=0x555555bc7680, idx_func=41, call_flags=call_flags@entry=0) at prep/fuzz/duktape.c:64142
#81 0x0000555555626498 in duk_handle_call_unprotected (call_flags=0, idx_func=<optimized out>, thr=0x555555bc7680)
    at prep/fuzz/duktape.c:64489
#82 duk_call_method (thr=thr@entry=0x2711, nargs=<optimized out>, nargs@entry=1) at prep/fuzz/duktape.c:14352
#83 0x000055555562d0bb in duk_hobject_getprop (thr=0x2711, thr@entry=0x555555bc7680, tv_obj=0x7fffffffc660, 
    tv_obj@entry=0x555555bc7bd0, tv_key=0x7fffffffc670) at prep/fuzz/duktape.c:56912
#84 0x000055555562f26e in duk_get_prop (thr=0x555555bc7680, obj_idx=<optimized out>) at prep/fuzz/duktape.c:16625
#85 0x00005555557eb665 in duk_unpack_array_like (thr=thr@entry=0x555555bc7680, idx=idx@entry=38) at prep/fuzz/duktape.c:23859
#86 0x00005555556220cf in duk__handle_specialfuncs_for_call (first=<optimized out>, call_flags=<synthetic pointer>, 
    func=<optimized out>, idx_func=<optimized out>, thr=0x555555bc7680) at prep/fuzz/duktape.c:62935
#87 duk__resolve_target_func_and_this_binding (call_flags=<synthetic pointer>, idx_func=36, thr=0x555555bc7680)
    at prep/fuzz/duktape.c:63360
#88 duk__handle_call_raw (thr=thr@entry=0x555555bc7680, idx_func=36, call_flags=call_flags@entry=0) at prep/fuzz/duktape.c:64142
#89 0x0000555555626498 in duk_handle_call_unprotected (call_flags=0, idx_func=<optimized out>, thr=0x555555bc7680)
    at prep/fuzz/duktape.c:64489
#90 duk_call_method (thr=thr@entry=0x2711, nargs=<optimized out>, nargs@entry=1) at prep/fuzz/duktape.c:14352
#91 0x000055555562d0bb in duk_hobject_getprop (thr=0x2711, thr@entry=0x555555bc7680, tv_obj=0x7fffffffc840, 
    tv_obj@entry=0x555555bc7b80, tv_key=0x7fffffffc850) at prep/fuzz/duktape.c:56912
#92 0x000055555562f26e in duk_get_prop (thr=0x555555bc7680, obj_idx=<optimized out>) at prep/fuzz/duktape.c:16625
#93 0x00005555557eb665 in duk_unpack_array_like (thr=thr@entry=0x555555bc7680, idx=idx@entry=33) at prep/fuzz/duktape.c:23859
#94 0x00005555556220cf in duk__handle_specialfuncs_for_call (first=<optimized out>, call_flags=<synthetic pointer>, 
    func=<optimized out>, idx_func=<optimized out>, thr=0x555555bc7680) at prep/fuzz/duktape.c:62935
#95 duk__resolve_target_func_and_this_binding (call_flags=<synthetic pointer>, idx_func=31, thr=0x555555bc7680)
    at prep/fuzz/duktape.c:63360
#96 duk__handle_call_raw (thr=thr@entry=0x555555bc7680, idx_func=31, call_flags=call_flags@entry=0) at prep/fuzz/duktape.c:64142
#97 0x0000555555626498 in duk_handle_call_unprotected (call_flags=0, idx_func=<optimized out>, thr=0x555555bc7680)
    at prep/fuzz/duktape.c:64489
#98 duk_call_method (thr=thr@entry=0x2711, nargs=<optimized out>, nargs@entry=1) at prep/fuzz/duktape.c:14352
#99 0x000055555562d0bb in duk_hobject_getprop (thr=0x2711, thr@entry=0x555555bc7680, tv_obj=0x7fffffffca20, 
    tv_obj@entry=0x555555bc7b30, tv_key=0x7fffffffca30) at prep/fuzz/duktape.c:56912
#100 0x000055555562f26e in duk_get_prop (thr=0x555555bc7680, obj_idx=<optimized out>) at prep/fuzz/duktape.c:16625
#101 0x00005555557eb665 in duk_unpack_array_like (thr=thr@entry=0x555555bc7680, idx=idx@entry=28) at prep/fuzz/duktape.c:23859
#102 0x00005555556220cf in duk__handle_specialfuncs_for_call (first=<optimized out>, call_flags=<synthetic pointer>, 
    func=<optimized out>, idx_func=<optimized out>, thr=0x555555bc7680) at prep/fuzz/duktape.c:62935
#103 duk__resolve_target_func_and_this_binding (call_flags=<synthetic pointer>, idx_func=26, thr=0x555555bc7680)
    at prep/fuzz/duktape.c:63360
#104 duk__handle_call_raw (thr=thr@entry=0x555555bc7680, idx_func=26, call_flags=call_flags@entry=0) at prep/fuzz/duktape.c:64142
#105 0x0000555555626498 in duk_handle_call_unprotected (call_flags=0, idx_func=<optimized out>, thr=0x555555bc7680)
    at prep/fuzz/duktape.c:64489
#106 duk_call_method (thr=thr@entry=0x2711, nargs=<optimized out>, nargs@entry=1) at prep/fuzz/duktape.c:14352
#107 0x000055555562d0bb in duk_hobject_getprop (thr=0x2711, thr@entry=0x555555bc7680, tv_obj=0x7fffffffcc00, 
    tv_obj@entry=0x555555bc7ae0, tv_key=0x7fffffffcc10) at prep/fuzz/duktape.c:56912
#108 0x000055555562f26e in duk_get_prop (thr=0x555555bc7680, obj_idx=<optimized out>) at prep/fuzz/duktape.c:16625
#109 0x00005555557eb665 in duk_unpack_array_like (thr=thr@entry=0x555555bc7680, idx=idx@entry=23) at prep/fuzz/duktape.c:23859
#110 0x00005555556220cf in duk__handle_specialfuncs_for_call (first=<optimized out>, call_flags=<synthetic pointer>, 
    func=<optimized out>, idx_func=<optimized out>, thr=0x555555bc7680) at prep/fuzz/duktape.c:62935
#111 duk__resolve_target_func_and_this_binding (call_flags=<synthetic pointer>, idx_func=21, thr=0x555555bc7680)
    at prep/fuzz/duktape.c:63360
#112 duk__handle_call_raw (thr=thr@entry=0x555555bc7680, idx_func=21, call_flags=call_flags@entry=0) at prep/fuzz/duktape.c:64142
#113 0x0000555555626498 in duk_handle_call_unprotected (call_flags=0, idx_func=<optimized out>, thr=0x555555bc7680)
    at prep/fuzz/duktape.c:64489
#114 duk_call_method (thr=thr@entry=0x2711, nargs=<optimized out>, nargs@entry=1) at prep/fuzz/duktape.c:14352
#115 0x000055555562d0bb in duk_hobject_getprop (thr=0x2711, thr@entry=0x555555bc7680, tv_obj=0x7fffffffcde0, 
    tv_obj@entry=0x555555bc7a90, tv_key=0x7fffffffcdf0) at prep/fuzz/duktape.c:56912
#116 0x000055555562f26e in duk_get_prop (thr=0x555555bc7680, obj_idx=<optimized out>) at prep/fuzz/duktape.c:16625
#117 0x00005555557eb665 in duk_unpack_array_like (thr=thr@entry=0x555555bc7680, idx=idx@entry=18) at prep/fuzz/duktape.c:23859
#118 0x00005555556220cf in duk__handle_specialfuncs_for_call (first=<optimized out>, call_flags=<synthetic pointer>, 
    func=<optimized out>, idx_func=<optimized out>, thr=0x555555bc7680) at prep/fuzz/duktape.c:62935
#119 duk__resolve_target_func_and_this_binding (call_flags=<synthetic pointer>, idx_func=16, thr=0x555555bc7680)
    at prep/fuzz/duktape.c:63360
#120 duk__handle_call_raw (thr=thr@entry=0x555555bc7680, idx_func=16, call_flags=call_flags@entry=0) at prep/fuzz/duktape.c:64142
#121 0x0000555555626498 in duk_handle_call_unprotected (call_flags=0, idx_func=<optimized out>, thr=0x555555bc7680)
    at prep/fuzz/duktape.c:64489
#122 duk_call_method (thr=thr@entry=0x2711, nargs=<optimized out>, nargs@entry=1) at prep/fuzz/duktape.c:14352
#123 0x000055555562d0bb in duk_hobject_getprop (thr=0x2711, thr@entry=0x555555bc7680, tv_obj=0x7fffffffcfc0, 
    tv_obj@entry=0x555555bc7a40, tv_key=0x7fffffffcfd0) at prep/fuzz/duktape.c:56912
#124 0x000055555562f26e in duk_get_prop (thr=0x555555bc7680, obj_idx=<optimized out>) at prep/fuzz/duktape.c:16625
#125 0x00005555557eb665 in duk_unpack_array_like (thr=thr@entry=0x555555bc7680, idx=idx@entry=13) at prep/fuzz/duktape.c:23859
#126 0x00005555556220cf in duk__handle_specialfuncs_for_call (first=<optimized out>, call_flags=<synthetic pointer>, 
    func=<optimized out>, idx_func=<optimized out>, thr=0x555555bc7680) at prep/fuzz/duktape.c:62935
#127 duk__resolve_target_func_and_this_binding (call_flags=<synthetic pointer>, idx_func=11, thr=0x555555bc7680)
    at prep/fuzz/duktape.c:63360
#128 duk__handle_call_raw (thr=thr@entry=0x555555bc7680, idx_func=11, call_flags=call_flags@entry=0) at prep/fuzz/duktape.c:64142
#129 0x0000555555626498 in duk_handle_call_unprotected (call_flags=0, idx_func=<optimized out>, thr=0x555555bc7680)
    at prep/fuzz/duktape.c:64489
#130 duk_call_method (thr=thr@entry=0x2711, nargs=<optimized out>, nargs@entry=1) at prep/fuzz/duktape.c:14352
#131 0x000055555562d0bb in duk_hobject_getprop (thr=0x2711, thr@entry=0x555555bc7680, tv_obj=0x7fffffffd1a0, 
    tv_obj@entry=0x555555bc79f0, tv_key=0x7fffffffd1b0) at prep/fuzz/duktape.c:56912
#132 0x000055555562f26e in duk_get_prop (thr=0x555555bc7680, obj_idx=<optimized out>) at prep/fuzz/duktape.c:16625
#133 0x00005555557eb665 in duk_unpack_array_like (thr=thr@entry=0x555555bc7680, idx=idx@entry=8) at prep/fuzz/duktape.c:23859
#134 0x00005555556220cf in duk__handle_specialfuncs_for_call (first=<optimized out>, call_flags=<synthetic pointer>, 
    func=<optimized out>, idx_func=<optimized out>, thr=0x555555bc7680) at prep/fuzz/duktape.c:62935
#135 duk__resolve_target_func_and_this_binding (call_flags=<synthetic pointer>, idx_func=6, thr=0x555555bc7680)
    at prep/fuzz/duktape.c:63360
#136 duk__handle_call_raw (thr=thr@entry=0x555555bc7680, idx_func=6, call_flags=call_flags@entry=0) at prep/fuzz/duktape.c:64142
#137 0x0000555555626498 in duk_handle_call_unprotected (call_flags=0, idx_func=<optimized out>, thr=0x555555bc7680)
    at prep/fuzz/duktape.c:64489
#138 duk_call_method (thr=thr@entry=0x2711, nargs=<optimized out>, nargs@entry=1) at prep/fuzz/duktape.c:14352
#139 0x000055555562d0bb in duk_hobject_getprop (thr=0x2711, thr@entry=0x555555bc7680, tv_obj=0x7fffffffd380, 
    tv_obj@entry=0x555555bc7990, tv_key=0x7fffffffd390) at prep/fuzz/duktape.c:56912
#140 0x000055555562f26e in duk_get_prop (thr=0x555555bc7680, obj_idx=<optimized out>) at prep/fuzz/duktape.c:16625
#141 0x0000555555837ec9 in duk_get_prop_stridx_short_raw (packed_args=4294836310, thr=0x555555bc7680) at prep/fuzz/duktape.c:16690
#142 duk_bi_function_prototype_bind (thr=0x555555bc7680) at prep/fuzz/duktape.c:33340
#143 0x000055555561f5b7 in duk__handle_call_raw (thr=thr@entry=0x555555bc7680, idx_func=idx_func@entry=2, 
    call_flags=call_flags@entry=8) at prep/fuzz/duktape.c:64343
#144 0x000055555556116d in duk_handle_call_unprotected (call_flags=8, idx_func=2, thr=0x555555bc7680) at prep/fuzz/duktape.c:64489
#145 duk__executor_handle_call (call_flags=8, nargs=2, idx=2, thr=0x555555bc7680) at prep/fuzz/duktape.c:10215
#146 duk__js_execute_bytecode_inner (entry_act=entry_act@entry=0x555555bd57a0, entry_thread=<optimized out>)
    at prep/fuzz/duktape.c:12289
#147 0x0000555555614f86 in duk_js_execute_bytecode (exec_thr=exec_thr@entry=0x555555bc7680) at prep/fuzz/duktape.c:76013
#148 0x000055555561db30 in duk__handle_call_raw (thr=0x555555bc7680, idx_func=<optimized out>, call_flags=0)
    at prep/fuzz/duktape.c:64307
#149 0x00005555558930b7 in wrapped_compile_execute (ctx=ctx@entry=0x555555bc7680, udata=udata@entry=0x0)
    at examples/cmdline/duk_cmdline.c:301
#150 0x00005555556370a7 in duk__handle_safe_call_inner (num_stack_rets=1, idx_retbase=0, entry_thread_state=1 '\001', 
    entry_curr_thread=0x0, entry_callstack_top=0, entry_valstack_bottom_byteoff=0, udata=0x0, 
    func=0x555555892cf0 <wrapped_compile_execute>, thr=0x555555bc7680) at prep/fuzz/duktape.c:64542
#151 duk_handle_safe_call (thr=0x555555bc7680, func=0x555555892cf0 <wrapped_compile_execute>, udata=0x0, 
    num_stack_args=<optimized out>, num_stack_rets=1) at prep/fuzz/duktape.c:64787
#152 0x0000555555893a53 in handle_fh (ctx=0x555555bc7680, f=0x555555bd9280, filename=0x7fffffffe1b7 "test.js", 
    bytecode_filename=0x0) at examples/cmdline/duk_cmdline.c:632
#153 0x000055555555b51b in handle_file (bytecode_filename=<optimized out>, filename=0x7fffffffe1b7 "test.js", ctx=0x555555bc7680)
    at examples/cmdline/duk_cmdline.c:691
#154 main (argc=2, argv=0x7fffffffdde8) at examples/cmdline/duk_cmdline.c:1465
```

###### Build script:

```bash
#!/bin/bash

git reset --hard origin/master
git pull origin master
rm -rf prep/fuzz duk
mkdir -p prep/fuzz

python2 tools/configure.py --output-directory prep/fuzz --source-directory src-input --config-metadata config --option-file $(dirname $0)/duktape-fuzzinator-options.yaml

gcc -o duk \
    -Iprep/fuzz \
    -D_POSIX_C_SOURCE=200809L \
    -pedantic -ansi -std=c99 -fstrict-aliasing -Wall -Wextra -Wunused-result -Wdeclaration-after-statement -Wunused-function -Wcast-qual -Wcast-align -Wshadow -Wunreachable-code   -Wmissing-prototypes -Wsign-conversion -Wsuggest-attribute=noreturn -fmax-errors=3 \
    -Ilinenoise \
    -Iexamples/cmdline \
    -Iexamples/alloc-logging \
    -Iexamples/alloc-torture \
    -Iexamples/alloc-hybrid \
    -Iexamples/debug-trans-socket \
    -Iextras/print-alert \
    -Iextras/console \
    -Iextras/logging \
    -Iextras/module-duktape \
    -Iextras/cbor \
    -O0 -g -ggdb \
    prep/fuzz/duktape.c \
    examples/cmdline/duk_cmdline.c \
    examples/alloc-logging/duk_alloc_logging.c \
    examples/alloc-torture/duk_alloc_torture.c \
    examples/alloc-hybrid/duk_alloc_hybrid.c \
    extras/print-alert/duk_print_alert.c \
    extras/console/duk_console.c \
    extras/logging/duk_logging.c \
    extras/module-duktape/duk_module_duktape.c \
    extras/cbor/duk_cbor.c \
    examples/debug-trans-socket/duk_trans_socket_unix.c \
    linenoise/linenoise.c \
    -lm

```

###### duktape-fuzzinator-options.yaml:

```yaml
DUK_USE_ASSERTIONS: true
DUK_USE_DEBUG: false

DUK_USE_ES6_OBJECT_PROTO_PROPERTY: true
DUK_USE_JX: true
DUK_USE_JC: true

DUK_USE_NONSTD_ARRAY_SPLICE_DELCOUNT: true
DUK_USE_NONSTD_JSON_ESC_U2028_U2029: true
DUK_USE_NONSTD_STRING_FROMCHARCODE_32BIT: true
DUK_USE_ES6_OBJECT_PROTO_PROPERTY: true
DUK_USE_ES6_OBJECT_SETPROTOTYPEOF: true
DUK_USE_ES6_PROXY: true
DUK_USE_ZERO_BUFFER_DATA: true
DUK_USE_SETJMP: true
DUK_USE_LIGHTFUNC_BUILTINS: true
DUK_USE_BUFFEROBJECT_SUPPORT: true
DUK_USE_FASTINT: true
DUK_USE_JSON_STRINGIFY_FASTPATH: true
DUK_USE_GLOBAL_BINDING: true
DUK_USE_PROMISE_BUILTIN: true

DUK_USE_FATAL_HANDLER:
  verbatim: |
    #define DUK_USE_FATAL_HANDLER(udata,msg) do { \
            const char *fatal_msg = (msg); /* avoid double evaluation */ \
            (void) udata; \
            fprintf(stderr, "*** FATAL ERROR: %s\n", fatal_msg ? fatal_msg : "no message"); \
            fflush(stderr); \
            abort(); \
        } while (0)

```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/) with [grammarinator](https://github.com/renatahodovan/grammarinator). </sup>

**Comment by svaarala** [comment]
The repro code in essence causes infinite recursion which should terminate with a RangeError when call stack limit is reached. The repeating loop is:
- duk_hobject_getprop()
- duk_handle_call_unprotected()
- duk__resolve_target_func_and_this_binding()
- duk__handle_specialfuncs_for_call()
- duk_unpack_array_like()
- duk_get_prop()
- duk_hobject_getprop() => loop

The loops seems to be kicked off as follows:
- The .bind() call reads `.length` of the function. However, the length getter captures the read.
- The getter is a callable Proxy (because Uint32Array is callable) so `.apply` trap is looked up.
- Because the Proxy trap table is TextEncoder, also callable, `Function.prototype.apply` is identified as the trap to call.
- When Function.prototype.apply() is called (this is handled by duk_js_call.c in practice) the argument array is unpacked to the value stack. This also happens to be a function `.length` lookup which retriggers teh `apply` trap again, leading to the loop.

This loop is triggered in call handling *before* there is a chance to update the call recursion depth counter. This prevents the artificial call stack limit from breaking out of the loop. This can be fixed by updating the call stack depth as early as possible which is in hindsight the right thing to do; with Proxy introduced, any property read can trigger a call loop.
