### ISSUE TITLE
longjmp crash when compiled with -O3

### ISSUE THREAD

**Issue by eduardsui** [svaarala/duktape#2057]
Hello,

I've noticed that if I try to use gcc -O3 on Windows and use for example duk_peval_string (or any other duk_p* functions), the program crashes.
```
#4  0x00007ffea4372e1a in msvcrt!_setjmpex () from C:\WINDOWS\System32\msvcrt.dll
#5  0x000000000047b2ca in duk_err_longjmp ()
#6  0x000000000049210f in duk_throw_raw ()
```
If I compile with -O2, everything works as expected. The compiler I am using is gcc (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0.

It is not a big deal (-O3 being known to be "buggy").

Thanks,
E.

**Comment by svaarala** [comment]
Good to know, it'd be interesting to know what's the root cause for the crash.

**Comment by eduardsui** [comment]
I'm trying to isolate this problem with a minimal program. It seems that there is some kind of interaction between duktape and usrsctp, just on windows. On linux, valgrind doesn't show anything wrong. Also, it happens only on 64 bit (-O3). On 32 bit everything seems fine. I will try to identify and fix this problem.

**Comment by eduardsui** [comment]
Got gdb backtrace, maybe somebody sees something:
```
Thread 5 received signal SIGSEGV, Segmentation fault.
[Switching to Thread 9732.0x34c]
0x00007ffe0b56383c in ntdll!RtlGetSecurityDescriptorRMControl () from C:\WINDOWS\SYSTEM32\ntdll.dll
(gdb) bt
#0  0x00007ffe0b56383c in ntdll!RtlGetSecurityDescriptorRMControl () from C:\WINDOWS\SYSTEM32\ntdll.dll
#1  0x00007ffe0b581a99 in ntdll!memset () from C:\WINDOWS\SYSTEM32\ntdll.dll
#2  0x00007ffe0b56b6e6 in ntdll!__C_specific_handler () from C:\WINDOWS\SYSTEM32\ntdll.dll
#3  0x00007ffe0b57f85d in ntdll!.chkstk () from C:\WINDOWS\SYSTEM32\ntdll.dll
#4  0x00007ffe0b4ee240 in ntdll!RtlUnwindEx () from C:\WINDOWS\SYSTEM32\ntdll.dll
#5  0x00007ffe097a2e1a in msvcrt!_setjmpex () from C:\WINDOWS\System32\msvcrt.dll
#6  0x000000000047b39a in duk_err_longjmp (thr=thr@entry=0xc4603d0) at duk_error_longjmp.c:99
#7  0x00000000004921df in duk_throw_raw (thr=thr@entry=0xc4603d0) at duk_api_stack.c:6363
#8  0x00000000004922ac in duk_js_compile (thr=thr@entry=0xc4603d0, src_buffer=0xc45c070 "some invalid js file",
    src_length=20, flags=flags@entry=3720) at duk_js_compiler.c:8017
#9  0x00000000004a1a0f in duk__do_compile (thr=0xc4603d0, udata=0x3b6bdd0) at duk_api_compile.c:106
#10 0x0000000000482340 in duk__handle_safe_call_inner (num_stack_rets=967, idx_retbase=<optimized out>,
    entry_thread_state=0 '\000', entry_curr_thread=0x0, udata=0xff656c, func=0x6261646100000001, thr=0x747d7d657d657364)
    at duk_js_call.c:2438
#11 duk_handle_safe_call (thr=0x747d7d657d657364, func=0x6261646100000001, udata=0xff656c, num_stack_args=<optimized out>,
    num_stack_rets=<optimized out>) at duk_js_call.c:2683
#12 0x00000000004a1e0a in duk_compile_raw (flags=3720, src_length=<optimized out>,
    src_buffer=0xe88 <error: Cannot access memory at address 0xe88>, thr=0xc4603d0) at duk_api_compile.c:162
#13 duk_eval_raw (thr=thr@entry=0xc4603d0, src_buffer=<optimized out>, src_buffer@entry=0xc45c070 "some invalid js file",
    src_length=src_length@entry=0, flags=flags@entry=3720) at duk_api_compile.c:29
#14 0x00000000004d1540 in edfs_key_data_load_js (key_data=key_data@entry=0x6fba1c0,
    js_data=js_data@entry=0xc45c070 "some invalid js file") at src/edfs_key_data.c:162
#15 0x00000000004ff949 in edfs_reload_app (edfs_context=edfs_context@entry=0x1a5820, key=key@entry=0x6fba1c0)
    at src/edfs_core.c:2139
```
I'm using multiple threads, but this happens in the same thread ... I'm almost sure that is something wrong in my code and not in duktape. The weird thing is that the problem shows only with -O3.

**Comment by eduardsui** [comment]
Ok, the problem is with setjmp/longjmp and -finline-function (set by -O3). If I compile my entire project with -O3 and just duktape with -O2, everything works. Seems that the offending compiler flag is -finline-function (-O3). If I compile with -O2 -finline-functions I get the same crash.

**Comment by eduardsui** [comment]
I think we can close this, being compiler-version-related.
