### ISSUE TITLE
Makefile screwed up with python 3.8

### ISSUE THREAD

**Issue by wenq1** [svaarala/duktape#2294]
I switched to python 3.8 (2.7 is no longer supported), and tried to make.

First it complains that linenoise folder already exists (the script should indeed check for that), and after removing the folder and tried again, complains about prep folder. removed and tried again, got the following.

````
iMac:duktape wc$ make -B
# git clone https://github.com/antirez/linenoise.git
# Use forked repo to get compile warnings fixed.
git clone -b fix-compile-warnings-duktape https://github.com/svaarala/linenoise.git
fatal: destination path 'linenoise' already exists and is not an empty directory.
make: *** [linenoise] Error 128
iMac:duktape wc$ 
iMac:duktape wc$ rm -fr linenoise/
iMac:duktape wc$ make -B
# git clone https://github.com/antirez/linenoise.git
# Use forked repo to get compile warnings fixed.
git clone -b fix-compile-warnings-duktape https://github.com/svaarala/linenoise.git
Cloning into 'linenoise'...
remote: Enumerating objects: 414, done.
remote: Total 414 (delta 0), reused 0 (delta 0), pack-reused 414
Receiving objects: 100% (414/414), 123.21 KiB | 35.00 KiB/s, done.
Resolving deltas: 100% (243/243), done.
mkdir: prep: File exists
make: *** [prep] Error 1
/usr/local/opt/python@3.8/bin/python3 tools/configure.py --output-directory ./prep/nondebug --source-directory src-input --config-metadata config --option-file util/makeduk_base.yaml --line-directives
Traceback (most recent call last):
  File "tools/configure.py", line 1005, in <module>
    main()
  File "tools/configure.py", line 315, in main
    get_duk_version(os.path.join(srcdir, 'duktape.h.in'))
  File "tools/configure.py", line 139, in get_duk_version
    m = r.match(line)
TypeError: cannot use a string pattern on a bytes-like object

````

**Comment by wenq1** [comment]
Closing as it is inactive.

**Comment by svaarala** [comment]
All Duktape tooling is Python2 only

**Comment by jirutka** [comment]
> All Duktape tooling is Python2 only

Maybe you missed that Python 2 is officially dead since January 1 2020 (see [Sunsetting Python 2](https://www.python.org/doc/sunset-python-2/)). The Linux distributions are gradually removing support for Python 2.

**Comment by svaarala** [comment]
I didn't miss that - all the tooling will be converted to Node.js and that is already in progress, see src-tools.

**Comment by jirutka** [comment]
That’s a great decision, to get rid of Python dependency! :+1:
