### ISSUE TITLE
How to compile Duktape for Windows ?

### ISSUE THREAD

**Issue by Honya2000** [svaarala/duktape#2410]
Hello,

I follow instructions in Readme:
1. Installed Python2.7
2. pip install PyYAML
3. python util\dist.py

But it gives immediate error:

****************************************************************************
*** Duktape python tooling is obsolete, migrate to JS-based tooling!     ***
*** This tool now internally invokes the JS-based tooling.               ***
*** Minimum Node.js version is 14.x.                                     ***
****************************************************************************

*** Executing JS-based tooling with command: ['node', 'd:\\Projects\\TMRW\\RoomGit\\tmrwNative\\third_party\\duktape\\util\\..\\src-tools\\index.js', 'dist', '--validate-git']

internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module '../extdeps/js-yaml'
Require stack:
- d:\Projects\TMRW\RoomGit\tmrwNative\third_party\duktape\src-tools\lib\util\yaml.js
- d:\Projects\TMRW\RoomGit\tmrwNative\third_party\duktape\src-tools\lib\util\fs.js
- d:\Projects\TMRW\RoomGit\tmrwNative\third_party\duktape\src-tools\lib\duktool\main.js
- d:\Projects\TMRW\RoomGit\tmrwNative\third_party\duktape\src-tools\index.js
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:841:27)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:1025:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:72:18)←[39m
    at Object.<anonymous> (d:\Projects\TMRW\RoomGit\tmrwNative\third_party\duktape\src-tools\lib\util\yaml.js:3:16)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1137:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:985:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:878:14)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:1025:19)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [
    ←[32m'd:\\Projects\\TMRW\\RoomGit\\tmrwNative\\third_party\\duktape\\src-tools\\lib\\util\\yaml.js'←[39m,
    ←[32m'd:\\Projects\\TMRW\\RoomGit\\tmrwNative\\third_party\\duktape\\src-tools\\lib\\util\\fs.js'←[39m,
    ←[32m'd:\\Projects\\TMRW\\RoomGit\\tmrwNative\\third_party\\duktape\\src-tools\\lib\\duktool\\main.js'←[39m,
    ←[32m'd:\\Projects\\TMRW\\RoomGit\\tmrwNative\\third_party\\duktape\\src-tools\\index.js'←[39m
  ]
}

What should I do ?

**Comment by huadream** [comment]
If you just want to compile, you can download this (https://github.com/svaarala/duktape/releases) and use the final files in the src directory.

**Comment by farism** [comment]
For some reason these utils [are in the gitignore](https://github.com/svaarala/duktape/blob/master/.gitignore#L42-L44)

I created the file `/src-tools/lib/extdeps/js-yaml.js` and used v3 https://github.com/nodeca/js-yaml/blob/v3/dist/js-yaml.js and it worked.
