### ISSUE TITLE
assertion failed: duk_is_string(ctx, -1) in duk_bi_string_prototype_replace

### ISSUE THREAD

**Issue by renatahodovan** [svaarala/duktape#492]
###### Duktape version:
    Checked revision: a0cfda4
    Build: debug
###### OS: 
    Ubuntu 15.10, x86_64
###### Test case:
```javascript
String.prototype.replace(RegExp.prototype);
```

###### Backtrace:
```
PANIC 54: assertion failed: duk_is_string(ctx, -1) (duk_bi_string.c:543) (segfaulting on purpose)

Program received signal SIGSEGV, Segmentation fault.
0x000000000040220e in duk_default_panic_handler (code=54, msg=0x50c678 "assertion failed: duk_is_string(ctx, -1) (duk_bi_string.c:543)")
    at duk_error_macros.c:157
157 duk_error_macros.c: No such file or directory.
(gdb) bt
#0  0x000000000040220e in duk_default_panic_handler (code=54, msg=0x50c678 "assertion failed: duk_is_string(ctx, -1) (duk_bi_string.c:543)")
    at duk_error_macros.c:157
#1  0x0000000000447a65 in duk_bi_string_prototype_replace (ctx=0x757d60) at duk_bi_string.c:543
#2  0x000000000046e67e in duk_handle_call (thr=0x757d60, num_stack_args=1, call_flags=0) at duk_js_call.c:1395
#3  0x00000000004876b6 in duk__js_execute_bytecode_inner (entry_thread=0x757d60, entry_callstack_top=1) at duk_js_executor.c:3356
#4  0x0000000000482eeb in duk_js_execute_bytecode (exec_thr=0x757d60) at duk_js_executor.c:2045
#5  0x000000000046ea42 in duk_handle_call (thr=0x757d60, num_stack_args=0, call_flags=0) at duk_js_call.c:1508
#6  0x00000000004071a8 in duk_call_method (ctx=0x757d60, nargs=0) at duk_api_call.c:84
#7  0x000000000049c82a in wrapped_compile_execute (ctx=0x757d60) at dist/examples/cmdline/duk_cmdline.c:243
#8  0x000000000046f9a5 in duk_handle_safe_call (thr=0x757d60, func=0x49c5a2 <wrapped_compile_execute>, num_stack_args=4, num_stack_rets=1)
    at duk_js_call.c:1930
#9  0x0000000000407dc7 in duk_safe_call (ctx=0x757d60, func=0x49c5a2 <wrapped_compile_execute>, nargs=4, nrets=1) at duk_api_call.c:221
#10 0x000000000049c9f5 in handle_fh (ctx=0x757d60, f=0x763f50, filename=0x7fffffffd8ce "test.js", bytecode_filename=0x0)
    at dist/examples/cmdline/duk_cmdline.c:376
#11 0x000000000049cb6f in handle_file (ctx=0x757d60, filename=0x7fffffffd8ce "test.js", bytecode_filename=0x0) at dist/examples/cmdline/duk_cmdline.c:429
#12 0x000000000049d50e in main (argc=2, argv=0x7fffffffd448) at dist/examples/cmdline/duk_cmdline.c:972
```

**Comment by svaarala** [comment]
Thanks, I'll fix the issue :)

**Comment by svaarala** [comment]
Without asserts this causes a segfault so I marked this a (potential) security issue.
